name: Terraform staging

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: staging
    steps:

    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

  deploy:
    name: Build
    runs-on: ubuntu-latest
    environment: staging
    needs: plan
    steps:

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0

